spring.application.name=Managio
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/managio}
spring.datasource.username=${DB_USERNAME:managio_user}
spring.datasource.password=${DB_PASSWORD:Nitinr@1103}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update



# OAuth2 - Google (Explicitly Enabled)
app.oauth.google.enabled=true
spring.security.oauth2.client.registration.google.client-id=302125256-slivpnbp8k1hncg6kvlqle084cd1kpe1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile



razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:dummy@example.com}
spring.mail.password=${SMTP_PASSWORD:dummy-password}



spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
app.mail.enabled=${MAIL_ENABLED:true}


app.security.jwt.access-secret=${JWT_SECRET:your-super-secret-access-key-minimum-32-characters-long-please-change}
app.security.jwt.refresh-secret=${JWT_REFRESH_SECRET:your-super-secret-refresh-key-minimum-32-characters-long-please-change}
app.security.jwt.access-expiry-seconds=900
app.security.jwt.refresh-expiry-seconds=2592000
app.security.jwt.issuer=managio

app.security.invitation-expiry-hours=72

app.member.min-password-length=6
app.member.enable-self-registration=true


