spring.application.name=Managio
spring.datasource.url=jdbc:mysql://localhost:3306/managio_db
spring.datasource.username=root
spring.datasource.password=Nitin@1103
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=3030

spring.security.oauth2.client.registration.google.client-id=302125256-slivpnbp8k1hncg6kvlqle084cd1kpe1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
